### ISSUE TITLE
Fix post view

### ISSUE THREAD

**Issue by MichaelCurrin** [dcode-youtube/single-page-app-vanilla-js#1]
Currently the PostView.js page renders the same content as Posts.js.

https://github.com/dcode-youtube/single-page-app-vanilla-js/blob/master/frontend/static/js/views/PostView.js

It doesn't have to work as a proper single post view but the heading and content should at least look different.

**Comment by MichaelCurrin** [comment]
I've implemented something basic on my fork with Posts and Post views

https://michaelcurrin.github.io/single-page-app-vanilla-js/

**Comment by dcode-youtube** [comment]
Thank you! Please create a pull request so I can merge those changes in

**Comment by MichaelCurrin** [comment]
See please PR #3

**Comment by dcode-youtube** [comment]
@MichaelCurrin thanks for contributing - I've merged that PR.
