### ISSUE TITLE
[Suggestion] Change default port from 5060 to something else

### ISSUE THREAD

**Issue by TissuePowder** [dcode-youtube/single-page-app-vanilla-js#9]
Currently the default port used by the app is 5060, which is considered unsafe by chrome browser. Trying to visit the address with such ports is restricted by chrome by default with ERR_UNSAFE_PORT error. This can be circumvented manually or just by editing the port in dotenv or server.js file, but I think it would be better if you change the port to something else.

Here is a list of ports that chrome considers unsafe.
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc

List for firefox.
https://www-archive.mozilla.org/projects/netlib/portbanning#portlist

**Comment by dcode-youtube** [comment]
Thanks @TissuePowder and @felix-d1strict. Merged #11
